- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check that .oh-my-zsh exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh -s -- --unattended
  become: false
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: false
  tags: *tags_for_zsh_tasks

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  become: false
  tags: *tags_for_zsh_tasks
